/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessLogsMock: typeof import('./components/logs/AccessLogsMock.vue')['default']
    AdminProjectDeleteDialog: typeof import('./components/admin/AdminProjectDeleteDialog.vue')['default']
    AdminProjectsPanel: typeof import('./components/admin/AdminProjectsPanel.vue')['default']
    AdminQuotaDialog: typeof import('./components/admin/AdminQuotaDialog.vue')['default']
    AdminStoragePanel: typeof import('./components/admin/AdminStoragePanel.vue')['default']
    AdminUsersPanel: typeof import('./components/admin/AdminUsersPanel.vue')['default']
    AppActionsCard: typeof import('./components/projects/AppActionsCard.vue')['default']
    AppConsoleCard: typeof import('./components/projects/AppConsoleCard.vue')['default']
    AppCreationEnvironmentSection: typeof import('./components/projects/AppCreationEnvironmentSection.vue')['default']
    AppCreationSourceCard: typeof import('./components/projects/AppCreationSourceCard.vue')['default']
    AppCreationSummary: typeof import('./components/projects/AppCreationSummary.vue')['default']
    AppDatabaseCard: typeof import('./components/projects/AppDatabaseCard.vue')['default']
    AppDetailsCard: typeof import('./components/projects/AppDetailsCard.vue')['default']
    AppEnvVarsCard: typeof import('./components/projects/AppEnvVarsCard.vue')['default']
    AppLogsCard: typeof import('./components/projects/AppLogsCard.vue')['default']
    AppPreviewCard: typeof import('./components/projects/AppPreviewCard.vue')['default']
    AppProcessScaleCard: typeof import('./components/projects/AppProcessScaleCard.vue')['default']
    AppServiceLinkDialog: typeof import('./components/projects/AppServiceLinkDialog.vue')['default']
    Components: typeof import('./components/index.vue')['default']
    DashboardComponent: typeof import('./components/dashboard/DashboardComponent.vue')['default']
    DocumentationComponent: typeof import('./components/documentation/DocumentationComponent.vue')['default']
    IconCloudDemo: typeof import('./components/demo/IconCloudDemo.vue')['default']
    InteractiveIconCloud: typeof import('./components/ui/InteractiveIconCloud.vue')['default']
    Login: typeof import('./components/login/index.vue')['default']
    LogViewer: typeof import('./components/logs/LogViewer.vue')['default']
    ProjectsComponent: typeof import('./components/projects/ProjectsComponent.vue')['default']
    RepoSelector: typeof import('./components/git/RepoSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCard: typeof import('./components/projects/ServiceCard.vue')['default']
    ServiceCreationForm: typeof import('./components/projects/ServiceCreationForm.vue')['default']
    ServiceLinkDialog: typeof import('./components/projects/ServiceLinkDialog.vue')['default']
    ServiceProvisionProgress: typeof import('./components/projects/ServiceProvisionProgress.vue')['default']
    SettingComponent: typeof import('./components/settings/SettingComponent.vue')['default']
    UnifiedLogsMock: typeof import('./components/logs/UnifiedLogsMock.vue')['default']
    UserAvatar: typeof import('./components/ui/UserAvatar.vue')['default']
  }
}
